// This file is auto-generated by @hey-api/openapi-ts

export type ApartmentCreate = {
    address: string;
    city: string;
    area_sqm?: (number | null);
    rooms?: (number | null);
    floor?: (number | null);
    building_year?: (number | null);
    current_price: number;
    description?: (string | null);
};

export type ApartmentPublic = {
    address: string;
    city: string;
    area_sqm?: (number | null);
    rooms?: (number | null);
    floor?: (number | null);
    building_year?: (number | null);
    current_price: number;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type ApartmentsPublic = {
    data: Array<ApartmentPublic>;
    count: number;
};

export type ApartmentUpdate = {
    address?: (string | null);
    city?: (string | null);
    area_sqm?: (number | null);
    rooms?: (number | null);
    floor?: (number | null);
    building_year?: (number | null);
    current_price?: (number | null);
    description?: (string | null);
};

export type ApartmentWithHistory = {
    address: string;
    city: string;
    area_sqm?: (number | null);
    rooms?: (number | null);
    floor?: (number | null);
    building_year?: (number | null);
    current_price: number;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
    price_history: Array<PriceHistoryPublic>;
    change_history: Array<ChangeHistoryPublic>;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChangeHistoryPublic = {
    field_name: string;
    old_value?: (string | null);
    new_value?: (string | null);
    id: string;
    apartment_id: string;
    changed_at: string;
    changed_by_id: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PriceHistoryPublic = {
    old_price: number;
    new_price: number;
    id: string;
    apartment_id: string;
    changed_at: string;
    changed_by_id: string;
};

export type PriceUpdate = {
    new_price: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ApartmentsReadApartmentsData = {
    limit?: number;
    skip?: number;
};

export type ApartmentsReadApartmentsResponse = (ApartmentsPublic);

export type ApartmentsCreateApartmentData = {
    requestBody: ApartmentCreate;
};

export type ApartmentsCreateApartmentResponse = (ApartmentPublic);

export type ApartmentsReadApartmentData = {
    id: string;
};

export type ApartmentsReadApartmentResponse = (ApartmentPublic);

export type ApartmentsUpdateApartmentEndpointData = {
    id: string;
    requestBody: ApartmentUpdate;
};

export type ApartmentsUpdateApartmentEndpointResponse = (ApartmentPublic);

export type ApartmentsDeleteApartmentData = {
    id: string;
};

export type ApartmentsDeleteApartmentResponse = (Message);

export type ApartmentsReadApartmentWithHistoryData = {
    id: string;
};

export type ApartmentsReadApartmentWithHistoryResponse = (ApartmentWithHistory);

export type ApartmentsReadPriceHistoryData = {
    id: string;
};

export type ApartmentsReadPriceHistoryResponse = (Array<PriceHistoryPublic>);

export type ApartmentsUpdatePriceData = {
    id: string;
    requestBody: PriceUpdate;
};

export type ApartmentsUpdatePriceResponse = (ApartmentPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);